version: '3.4'

services:

  web:
    container_name: web
    build: .
    command: 
      gunicorn -b 0.0.0.0:5000
        --reload
        "baseapp.app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/baseapp'
    ports:
      - 5000:5000